# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_authorities_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.Neighbourhood'),
            preserve_default=False,
        ),
    ]
